# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8725967ad307626876dd8e211c25275816b7975428021213b0f06c520844228a03483a5cb4a8260c7ce335658f5d5c713778a02114dca3baa8af94a73f2c69e4

test:
  secret_key_base: ee4b23d0d973ad297beadd4a0abf44143f786a078f5d8bd46cbc8d370ea57ed4462f1e89b7c6d46c57ce9e4b20201e6af981a6568a4ec3e1cdf9453a982184be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
